baseurl = "http://www.surrealanalysis.com/"
languageCode = "en-us"
title = "Surreal Analysis"

[Params]
  logo = "img/infinity.png"


[Author]
  name = "Kevin Greene"
  email = "kevindgreene@gmail.com"
  github = "KevinGreene"
  twitter = "SurrealAnalysis"
  linkedin = "in/kevindgreene"

[[menu.main]]
    name = "about me"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
